// Full-site Hindi <-> English UI toggle (F35). The site's interface text is authored in Hindi; the English is a
// dictionary of UI phrases (shared/i18n_en.json, generated by scripts/build_i18n.py) applied to the page's TEXT
// NODES at runtime -- so it also covers text that app.js renders dynamically (a MutationObserver translates new nodes).
// Question content (stems, options, explanations, tables, discussion posts) is deliberately NEVER translated here:
// those have their own Hindi/English switch where a question exists in both languages.

const SKIP = "[data-notranslate],.question-text,.option,.explanation-box,.daily-q,.daily-opt,.daily-fact,.match-table,.q-line,.fx-hit,.fx-flash,.fx-comment,.bm-q,.blog-body,textarea,input,select,script,style,code";
const DEV = /[ऀ-ॿ]/;
let DICT = null, RE = null;

export const getLang = () => { try { return localStorage.getItem("lang") || "hi"; } catch (e) { return "hi"; } };
export function setLang(l) { try { localStorage.setItem("lang", l); } catch (e) {} location.reload(); }

function build(dict) {
  DICT = dict;
  const keys = Object.keys(dict).filter((k) => k.trim().length >= 2).sort((a, b) => b.length - a.length);
  const body = keys.map((k) => k.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
  // A phrase only matches as a whole word: never inside a longer Devanagari word (e.g. "जन" inside "राजनीतिक").
  const range = String.fromCharCode(0x900) + "-" + String.fromCharCode(0x97F);
  try { RE = new RegExp("(?<![" + range + "])(?:" + body + ")(?![" + range + "])", "g"); }
  catch (e) { RE = new RegExp(body, "g"); }
}

function tr(text) {
  const t = text.trim();
  if (DICT[t]) return text.replace(t, DICT[t]);
  return text.replace(RE, (m) => DICT[m] ?? DICT[m.trim()] ?? m);
}

function translateNode(node) {
  if (node.nodeType === 3) {
    if (DEV.test(node.nodeValue) && !node.parentElement?.closest(SKIP)) node.nodeValue = tr(node.nodeValue);
    return;
  }
  if (node.nodeType !== 1 || node.matches?.(SKIP)) return;
  for (const a of ["title", "placeholder", "aria-label", "alt"]) {
    const v = node.getAttribute?.(a);
    if (v && DEV.test(v) && !node.closest(SKIP)) node.setAttribute(a, tr(v));
  }
  node.childNodes.forEach(translateNode);
}

export async function initI18n() {
  const btn = document.getElementById("lang-toggle");
  const lang = getLang();
  if (btn) { btn.textContent = lang === "en" ? "हिं" : "EN"; btn.title = lang === "en" ? "हिन्दी में देखें" : "View in English"; btn.onclick = () => setLang(lang === "en" ? "hi" : "en"); }
  document.documentElement.lang = lang;
  if (lang !== "en") return;
  try {
    const res = await fetch("/shared/i18n_en.json?v=2");
    build(await res.json());
  } catch (e) { return; }
  translateNode(document.body);
  let queued = false;
  const pending = new Set();
  new MutationObserver((muts) => {
    muts.forEach((m) => { m.addedNodes.forEach((n) => pending.add(n)); if (m.type === "characterData") pending.add(m.target); });
    if (!queued) { queued = true; setTimeout(() => { queued = false; const nodes = [...pending]; pending.clear(); nodes.forEach(translateNode); }, 40); }
  }).observe(document.body, { childList: true, subtree: true, characterData: true });
}
